### ISSUE TITLE
internal time.sleep(0.003) hacks are required but limit speed

### ISSUE THREAD

**Issue by gpshead** [adafruit/Adafruit_CircuitPython_turtle#10]
Wanting to speed it up before speed and turtle hiding are implemented i noticed the `time.sleep(0.003)` calls in the code and figured I'd start there as a quick hack.

Removing those "does" speed it up.  It also messes up the drawing with only a fraction of pixels making it to the display (on a pygamer under circuitpython 4.1.0beta1).  There appears to be a displayio related race condition those sleeps are working around?

**Comment by ladyada** [comment]
yep, at this time we only redraw what the sprite moves over, if its too fast, we dont catch that. we'll add bitmap-change-draws at some point but it isnt supported yet, so this works instead :)

**Comment by tannewt** [comment]
This hack can go away once https://github.com/adafruit/circuitpython/issues/1981 is fixed.

**Comment by kattni** [comment]
@tannewt It looks https://github.com/adafruit/circuitpython/issues/1981 has been fixed. Can this issue be closed?

**Comment by ladyada** [comment]
would be lovely if someone could test and do a PR for it, dont close until that's done :)

**Comment by tannewt** [comment]
Right, we still need the sleeps removed from this library.
