### ISSUE TITLE
'Vec2D' object is not subscriptable

### ISSUE THREAD

**Issue by reversefold** [adafruit/Adafruit_CircuitPython_turtle#17]
Duplicate of https://github.com/adafruit/circuitpython/issues/2503. Opened here to help users who may look here. See the link for a full explanation.

A simple workaround if you run into this is to change the Vec2D class to have a tuple instead of extending tuple:
```
class Vec2D(object):
    def __init__(self, x, y):
        self.tup = (x, y)

    def __getitem__(self, i):
        return self.tup[i]
```

**Comment by dhalbert** [comment]
Should be fixed by https://github.com/adafruit/circuitpython/pull/2504
