### ISSUE TITLE
Pylint: assignment-from-no-return

### ISSUE THREAD

**Issue by dherrada** [adafruit/Adafruit_CircuitPython_turtle#20]
```
************* Module turtle_koch
examples/turtle_koch.py:7:8: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
************* Module turtle_overlayed_koch
examples/turtle_overlayed_koch.py:9:8: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
```
https://github.com/adafruit/Adafruit_CircuitPython_turtle/blob/c2d86f2f24bf1cf783bc3cce9bf59373e95dc242/examples/turtle_koch.py#L4:8

https://github.com/adafruit/Adafruit_CircuitPython_turtle/blob/c2d86f2f24bf1cf783bc3cce9bf59373e95dc242/examples/turtle_koch.py#L7:9

I'm not exactly sure why this is even being done, I would test just having it do `turtle.forward(line_length)` but I don't have the hardware with me to test.

@dastels Any insight into this?

Referencing main issue: adafruit/Adafruit_CircuitPython_Bundle#232
@kattni

**Comment by tannewt** [comment]
It looks like it can be safely removed to me.
