### ISSUE TITLE
Missing Type Annotations

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_turtle#27]
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_turtle.py:97
- [ ] adafruit_turtle.py:100
- [ ] adafruit_turtle.py:103
- [ ] adafruit_turtle.py:108
- [ ] adafruit_turtle.py:113
- [ ] adafruit_turtle.py:122
- [ ] adafruit_turtle.py:144
- [ ] adafruit_turtle.py:264
- [ ] adafruit_turtle.py:279
- [ ] adafruit_turtle.py:291
- [ ] adafruit_turtle.py:305
- [ ] adafruit_turtle.py:320
- [ ] adafruit_turtle.py:402
- [ ] adafruit_turtle.py:411
- [ ] adafruit_turtle.py:420
- [ ] adafruit_turtle.py:449
- [ ] adafruit_turtle.py:529
- [ ] adafruit_turtle.py:573
- [ ] adafruit_turtle.py:605
- [ ] adafruit_turtle.py:638
- [ ] adafruit_turtle.py:684
- [ ] adafruit_turtle.py:707
- [ ] adafruit_turtle.py:734
- [ ] adafruit_turtle.py:767
- [ ] adafruit_turtle.py:785
- [ ] adafruit_turtle.py:794
- [ ] adafruit_turtle.py:808
- [ ] adafruit_turtle.py:866
- [ ] adafruit_turtle.py:885
- [ ] adafruit_turtle.py:890
- [ ] adafruit_turtle.py:918
- [ ] adafruit_turtle.py:952
- [ ] adafruit_turtle.py:1044
- [ ] adafruit_turtle.py:1123
- [ ] adafruit_turtle.py:1168

**Comment by process1183** [comment]
Hi! I'll work on this one!

**Comment by patenaud** [comment]
Denis Patenaude- Pycon2023 sprint - will be working on this issue.

**Comment by rrahkola** [comment]
picking up this issue...

**Comment by rrahkola** [comment]
Hi @FoamyGuy and @tekktrik -- I'm interested in doing a good job with this, but I encountered a function which works multiple ways for different inputs, `Turtle.goto(x1, y1)` (e.g. [this version](https://github.com/adafruit/Adafruit_CircuitPython_turtle/blob/87ee248a953a4c3fc307881e21d1b697c0a12c4b/adafruit_turtle.py#L325-L333)).  I think a neat way to resolve this would be to use the **[@overload](https://docs.python.org/3.8/library/typing.html#typing.overload)** annotation, but I'm not sure it's supported by the CircuitPython library.  Could either of you provide some guidance here?

**Comment by FoamyGuy** [comment]
Quick test on a Feather S2 TFT seems to indicate that we don't have the ability to use that syntax currently:
```
code.py output:
Traceback (most recent call last):
  File "code.py", line 5, in <module>
  File "/lib/adafruit_turtle.py", line 147, in <module>
  File "/lib/adafruit_turtle.py", line 330, in turtle
NameError: name 'overload' is not defined
```
For now I think the best we can do is `Union` for x1 and Optional for y1. 

I don't know if we'd really want to change the API at this point, but it might be better in the long run to change the function to only work one way or the other. I'm not sure the convenience of being able to pass two arguments vs. a tuple with two values is outweighing the added complexity for typing and documentation.
