### ISSUE TITLE
Add to CircuitPython RTD

### ISSUE THREAD

**Issue by dastels** [adafruit/Adafruit_CircuitPython_turtle#7]
https://readthedocs.org/projects/circuitpython-turtle-graphics/

**Comment by kattni** [comment]
@dastels This was not done correctly. the URL should read readthedocs.org/projects/Adafruit_CircuitPython_turtle. There is no way to change the URL on an existing project, you must delete it and recreate it. When you enter the "Name" when importing it should be "Adafruit CircuitPython turtle" (no underscores). Then add me and adabot as maintainers.

**Comment by kattni** [comment]
There was an issue with the setup. Should be resolved and done now.
